name: ai-mart-platform

services:
  # user_services:
  #   image: user-mart-api:latest
  #   build:
  #     context: ./user_services
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - ./user-service:/code # Sync local development directory with the container
  #   depends_on:
  #     - broker
  #     - postgres_db
  #   ports:
  #     - "8008:8000" # Expose container port 8000 to host port 8000
  
  # Product_services:
  #   image: product-mart-api:latest
  #   build:
  #     context: ./Product_services
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - ./product-service:/code # Sync local development directory with the container
  #   depends_on:
  #     - broker
  #     - postgres_product_db
  #   ports:
  #     - "8005:8000" # Expose container port 8000 to host port 8000

  # order_service:
  #   image: order-mart-api:latest
  #   build:
  #     context: ./order_service
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - ./order-service:/code # Sync local development directory with the container
  #   depends_on:
  #     - broker
  #     - postgres_user_db
  #   ports:
  #     - "8007:8000" # Expose container port 8000 to host port 8000

  inventory_service:
    image: inventory-mart-api:latest
    build:
      context: ./Inventory_services
      dockerfile: Dockerfile.dev
    volumes:
      - ./inventory_services:/code # Sync local development directory with the container
    depends_on:
      - broker
      - postgres_inventory_db
    ports:
      - "8001:8001" # Expose container port 8000 to host port 8000



  postgres_db:
    image: postgres:latest # Use the official PostgreSQL image
    restart: always
    container_name: PostgresCont
    environment:
      - POSTGRES_USER=neobdb_owner
      - POSTGRES_PASSWORD=1tAkJjDgBfv6
      - POSTGRES_DB=neobdb
    ports:
      - "5480:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data

  # postgres_user_db:
  #   image: postgres:latest # Use the official PostgreSQL image
  #   restart: always
  #   container_name: PostgresUserCont
  #   environment:
  #     - POSTGRES_USER=neobdb_owner
  #     - POSTGRES_PASSWORD=1tAkJjDgBfv6
  #     - POSTGRES_DB=neobdb
  #   ports:
  #     - "5481:5432"
  #   volumes:
  #     - postgres_user_db:/var/lib/postgresql/data

  # postgres_order_db:
  #   image: postgres:latest # Use the official PostgreSQL image
  #   restart: always
  #   container_name: PostgresOrderCont
  #   environment:
  #     - POSTGRES_USER=neobdb_owner
  #     - POSTGRES_PASSWORD=1tAkJjDgBfv6
  #     - POSTGRES_DB=neobdb
  #   ports:
  #     - "5482:5432"
  #   volumes:
  #     - postgres_order_db:/var/lib/postgresql/data


  # postgres_product_db:
  #   image: postgres:latest # Use the official PostgreSQL image
  #   restart: always
  #   container_name: PostgresProductsCont
  #   environment:
  #     - POSTGRES_USER=neobdb_owner
  #     - POSTGRES_PASSWORD=1tAkJjDgBfv6
  #     - POSTGRES_DB=neobdb
  #   ports:
  #     - "5483:5432"
  #   volumes:
  #     - postgres_product_db:/var/lib/postgresql/data

  postgres_inventory_db:
    image: postgres:latest # Use the official PostgreSQL image
    restart: always
    container_name: PostgresInventoryCont
    environment:
      - POSTGRES_USER=neobdb_owner
      - POSTGRES_PASSWORD=1tAkJjDgBfv6
      - POSTGRES_DB=neobdb
    ports:
      - "5484:5432"
    volumes:
      - postgres_inventory_db:/var/lib/postgresql/data


  broker:
    image: apache/kafka:3.7.0
    hostname: broker
    container_name: broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT_HOST://localhost:9092,PLAINTEXT://broker:19092"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@broker:29093"
      KAFKA_LISTENERS: "CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      CLUSTER_ID: "4L6g3nShT-eMCtK--X86sw"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: "Local Kafka Cluster"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "broker:19092"
      DYNAMIC_CONFIG_ENABLED: "true"
    depends_on:
      - broker

volumes:
  postgres_db:
    driver: local
  # postgres_product_db:
  #   driver: local
  postgres_inventory_db:
    driver: local
  postgres_user_db:
    driver: local
  # postgres_order_db:
  #   driver: local

networks:
  default:
    driver: bridge
